site_name: "DOCS MNGT"
theme:
  name: 'material'
  logo: './files/logo-dark.webp'
  features:
    - content.code.copy
    - content.code.select
    - content.tabs.link
  palette:
    - scheme: default
      primary: dark-blue
      toggle:
        icon: material/weather-night
        name: Dark Mode
    - scheme: slate
      primary: dark-blue
      toggle:
        icon: material/weather-sunny
        name: Light Mode

plugins:
  - encryptcontent:
      title_prefix: 'üîí '
      global_password: !ENV [PASSWORD, 'mngt']
  - link-embeds:
      enabled: true
      name_default: "Untitled Link"
      desc_default: " "
      image_default: "https://github.com/Aetherinox/mkdocs-link-embeds/assets/118329232/c0298d98-0910-4235-a88f-0c3e2f704ba7"
      image_disabled: false
      favicon_default: "https://github.com/Aetherinox/mkdocs-link-embeds/assets/118329232/b37da9c6-6f17-4c3f-9c94-c346a6f31bfa"
      favicon_disabled: true
      favicon_size: 10
      target: "blank"
      accent: "FFFFFF1A"
      verbose: false

markdown_extensions:
  - admonition
  - pymdownx.tasklist  # Lista de tarefas
  - pymdownx.emoji  # Emojis
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format


extra_css:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.css
  - ./stylesheets/link-embeds.css
extra_javascript:
  - https://unpkg.com/mermaid@8.5.1/dist/mermaid.min.js


nav:
  - Home: 'index.md'
  - AI:
    - Guias:
      - 1 - IA Aplicada para desenvolvedores em empresas: 'ai/guides/1-IA-aplicada-para-desenvolvedores-em-empresas.md'
      - 4 - Integra√ß√£o e Automa√ß√£o com IA em Neg√≥cios (Guia Avan√ßado): 'ai/guides/4-integra√ß√£o-e-automacao-com-IA-em-negocios.md'
    - Ferramentas:
      - OpenWebUI: 'ai/tools/openwebui.md'
    - Descobertas:
      - Oportunidades de aplica√ß√£o de IA nos neg√≥cios do Grupo MNGT: 'ai/discovery/oportunidades.md'
  - Credentials:
    - ChatGPT: 'credentials/chatgpt.md'
    - SupaBase: 'credentials/supabase.md'
    - APP MNGT: 'credentials/app-mngt.md'
    - Servidor API: 'credentials/server-api-mngt.md'
    - Wordpress: 'credentials/wordpress.md'
    - Email Mais Armazem: 'credentials/email-mais-armazem.md'
    - Email Gabriel: 'credentials/email-gabriel.md'
    - Email Devs: 'credentials/email-devs.md'
    - API Mobbus: 'credentials/api-mobbus.md'
    - API Prevision: 'credentials/api-prevision.md'
    - API Sienge: 'credentials/api-sienge.md'
    - API Softexpert: 'credentials/api-softexpert.md'
  - Ferramentas:
    - Evolution API: 'tools/evolution-api.md'
  - Documentation:
      - Documentation: 'documentation/documentacao.md'
      - API Sienge:
          - API Sienge: 'documentation/documentacao/api-sienge.md'
          - Modulo Complementar: 'documentation/documentacao/api-sienge/0-modulo-complementar.md'
          - Modulo de Apoio Cadastros Base: 'documentation/documentacao/api-sienge/1-modulo-de-apoio-cadastros-base.md'
          - Modulo Financeiro: 'documentation/documentacao/api-sienge/2-modulo-financeiro.md'
          - Modulo de Suprimentos Compras e Estoque: 'documentation/documentacao/api-sienge/3-modulo-de-suprimentos-compras-e-estoque.md'
          - Modulo de Engenharia e Custos: 'documentation/documentacao/api-sienge/4-modulo-de-engenharia-e-custos.md'
          - Modulo Comercial Vendas e CRM: 'documentation/documentacao/api-sienge/5-modulo-comercial-vendas-e-crm.md'
      - Registro de Reunioes:
          - Registro de Reunioes: 'documentation/documentacao/registro-de-reunioes.md'
          - Automatizacao Processo Contas a Pagar: 'documentation/documentacao/registro-de-reunioes/automatizacao-processo-contas-a-pagar.md'
          - Mobuss Softexpert: 'documentation/documentacao/registro-de-reunioes/mobuss-softexpert.md'
          - Registro Reuniao 05-11: 'documentation/documentacao/registro-de-reunioes/registro-reuniao-05-11-1.md'
          - Registro Reuniao 10-11: 'documentation/documentacao/registro-de-reunioes/registro-reuniao-10-11-1.md'
      - Visita Rio Claro:
          - Visita Rio Claro: 'documentation/documentacao/visita-rio-claro.md'
          - Administrativo Comercial e Contratos: 'documentation/documentacao/visita-rio-claro/administrativo-comercial-e-contratos.md'
          - Agencia: 'documentation/documentacao/visita-rio-claro/agencia.md'
          - Compras: 'documentation/documentacao/visita-rio-claro/compras.md'
          - Conclusoes: 'documentation/documentacao/visita-rio-claro/conclusoes.md'
          - Dia 1 08-12: 'documentation/documentacao/visita-rio-claro/dia-1-08-12.md'
          - Financeiro: 'documentation/documentacao/visita-rio-claro/financeiro.md'
          - House: 'documentation/documentacao/visita-rio-claro/house.md'
          - Incorporacao: 'documentation/documentacao/visita-rio-claro/incorporacao.md'
          - M2log Mais Armazem: 'documentation/documentacao/visita-rio-claro/m2log-mais-armazem.md'
          - Orcamento: 'documentation/documentacao/visita-rio-claro/orcamento.md'
          - Planejamento e Medicao: 'documentation/documentacao/visita-rio-claro/planejamento-e-medicao.md'
          - Produtos: 'documentation/documentacao/visita-rio-claro/produtos.md'
          - Projetos: 'documentation/documentacao/visita-rio-claro/projetos.md'
          - Prospeccao: 'documentation/documentacao/visita-rio-claro/prospeccao.md'
          - Qualidade: 'documentation/documentacao/visita-rio-claro/qualidade.md'
          - SAC: 'documentation/documentacao/visita-rio-claro/sac.md'
          - Seguranca: 'documentation/documentacao/visita-rio-claro/seguranca.md'
          - Visita as Obras: 'documentation/documentacao/visita-rio-claro/visita-as-obras.md'
  - Tasks:
    - Tarefas: 'tasks/tarefas.md'
    - Farol de Compras: 'tasks/tarefas/farol-de-compras.md'
  - Infra:
    - Start: 'infra/start.md'
